### ISSUE TITLE
replace the white with green

### ISSUE THREAD

**Issue by zramctl** [mollersuite/website#3]
dawg the website fire and all but bro 😭 

![image](https://github.com/user-attachments/assets/8537fe09-32dd-42da-b4ae-9362c12e46b1)

the white does not match that much

**Comment by zramctl** [comment]
nah but new spaceness website coming soon might have to skid this 😎

**Comment by zramctl** [comment]
now THIS is quality gang
![image](https://github.com/user-attachments/assets/639734a5-d486-4efe-b23a-0f34023c2468)

**Comment by zramctl** [comment]
wait hm that shit looks ass 🔥

**Comment by zramctl** [comment]
and wtf is the problem with "If it needs a toggle, then remove it" like doesn't that just like remove more customizability on behalf of the user

**Comment by zramctl** [comment]
etcetera might be retarded 🧠❌

**Comment by IncognitoTGT** [comment]
thats a lot of yap

**Comment by zramctl** [comment]
@IncognitoTGT stfu dumbass

**Comment by Jack5079** [comment]
> and wtf is the problem with "If it needs a toggle, then remove it" like doesn't that just like remove more customizability on behalf of the user

Yes https://gnome.org if your features need to be turned off they're bad features

**Comment by Jack5079** [comment]
> > and wtf is the problem with "If it needs a toggle, then remove it" like doesn't that just like remove more customizability on behalf of the user
> 
> 
> If your features need to be turned off they're bad features and the feature should be removed that's what i meant to say

I have flashbacks of software like Grapejuice that was absolutely awful to use because of the way they did settings

**Comment by Jack5079** [comment]
To address your original issue: Green is the Etcetera accent color, doing this would be like making all the headings blue on a normal webpage, it would make links harder to discern

**Comment by zramctl** [comment]
> To address your original issue: Green is the Etcetera accent color, doing this would be like making all the headings blue on a normal webpage, it would make links harder to discern

ohh makes sense ok

**Comment by zramctl** [comment]
@Jack5079 also even though this is closed im lowkey sorry for opening an issue i know that you no longer want to hear from me and im actually surprised you responded so calmly, take care bro
